//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KostinaVDEntities1 : DbContext
    {
        private static KostinaVDEntities1 _context;
        public KostinaVDEntities1()
            : base("name=KostinaVDEntities1")
        {
        }

        public static KostinaVDEntities1 GetContext()
        {
            if (_context == null)
            
                _context = new KostinaVDEntities1();
                return _context;
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Materiali> Table_Materiali { get; set; }
    }
}
