//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Materiali
    {
        public int Артикул { get; set; }
        public Nullable<int> Размер { get; set; }
        public string Цвет { get; set; }
        public Nullable<int> Стоимость { get; set; }
    }
}
